image: 
  name: "continuumio/miniconda3:latest"

before_script:
  - conda config --append envs_dirs ./vendor/conda
  - conda env create -f conda.yml -p ./vendor/conda/$BASE_ENV
  - source activate $BASE_ENV

variables:
  BASE_ENV: seq2ml

stages:
  - build
  - test

build:
  stage: build
  script:
    - R --vanilla -e 'devtools::build()'
  only:
    - merge_requests

test:
  stage: test
  script:
    - R --vanilla -e 'devtools::check()'
  only:
    - merge_requests
    
