image: 
  name: "continuumio/miniconda3:latest"

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda config --append envs_dirs ./vendor/conda
  - conda env create -f conda.yml -p ./vendor/conda/$BASE_ENV
  - source activate $BASE_ENV
  - R --vanilla -e 'keras::install_keras(tensorflow = "default")'
variables:
  BASE_ENV: seq2ml
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - coverage

build:
  stage: build
  script:
    - R --vanilla -e 'devtools::build()'
  only:
    - merge_requests
    - master

document:
  stage: test
  script:
    - R --vanilla -e 'devtools::build()'
    - R --vanilla -e 'devtools::document()'
  only:
    - merge_requests
    - master

test:
  stage: test
  script:
    - R --vanilla -e 'devtools::check()'
  only:
    - merge_requests
    - master

coverage:
  stage: coverage
  script:
    - R --vanilla -e 'covr::package_coverage(type = c("tests", "examples"))'
  only:
    - merge_requests
    - master

